### ISSUE TITLE
ADF Examples Wiki Variable Clarification

### ISSUE THREAD

**Issue by justin-richling** [NCAR/ADF#128]
In the Wiki [ADF example tutorial docs](https://github.com/NCAR/ADF/wiki/ADF--examples#running-a-cam-vs-cam-comparison-on-casper):

Part 7) Setting Variables in ```config_cam_baseline_example.yaml```

The tutorial is based off variable order of appearance:
* diag_basic_info
    - cam_case_name
    - cam_climo_loc
    - cam_baseline_case_name
    - cam_baseline_climo_loc
    - cam_regrid_loc
    - cam_diag_plot_loc

* diag_cam_climo
    - cam_hist_loc
    - start_year
    - end_year
    - cam_ts_loc

* diag_cam_baseline_climo
    - cam_hist_loc
    - start_year
    - end_year
    - cam_ts_loc

---

When going through the current ```config_cam_baseline_example.yaml``` file, I noticed the order is now:
* diag_basic_info
    - cam_regrid_loc
    - cam_diag_plot_loc

* diag_cam_climo
    - cam_case_name
    - cam_hist_loc
    - cam_climo_loc
    - start_year
    - end_year
    - cam_ts_loc

* diag_cam_baseline_climo
    - cam_hist_loc
    - cam_climo_loc
    - start_year
    - end_year
    - cam_ts_loc

```cam_baseline_case_name``` and ```cam_baseline_climo_loc``` are no longer in the yaml file

---

Also in ```yaml``` file, the third set of variables ```diag_cam_baseline_climo``` section, there is a slight typo:
```#Location of baseline CAM cliimatologies:```

**Comment by justin-richling** [comment]
I'm sure this is probably already on the to-do list somewhere, but I would be happy to help

**Comment by bitterbark** [comment]
I've found that the wiki pages are easy enough to edit that it's worth just
doing it rather than making a list somewhere. For larger changes, I usually
check with the group, but for the two you mention, I think you should just
edit them. You can blame me if someone yells at you. (Anyone else feel free
to disagree). But an actual new user is invaluable for finding those kinds
of errors.

**Comment by justin-richling** [comment]
Sounds good, thanks Dani. I also updated the conda env instructions that CISL now recommends and to match the instructions in the [ADF diagnostics package examples](https://github.com/NCAR/ADF/wiki/ADF-diagnostics-package-examples) wiki (steps 2 and 3). 

If someone could just double check the updated variables, this should be good to close.

**Comment by justin-richling** [comment]
fixes PR [#129](https://github.com/NCAR/ADF/pull/129)

**Comment by nusbaume** [comment]
Thanks @justin-richling! There was only one extra variable that was missing, so I just went ahead and added it.  Otherwise everything looks good to me, so I'll go ahead and close this issue (it can always be re-opened if need be).  I also agree with @bitterbark that in general don't feel like you need to make an issue when making simple changes to the wiki (they are really just needed for source code changes).

Finally, as an FYI to you both, I found that there were actually two versions  of the same wiki page on this repo with slightly different instructions, and with various links throughout the repo pointing to one or the other in an inconsistent fashion.  I thus went ahead and tried to merge the two pages, so that there is only one official version, and also tried to modify any URLs that pointed to the non-merged wiki page. However, if you do run into a broken link on the wiki then this may be the reason why.
