### ISSUE TITLE
variables in climos-regrid are double

### ISSUE THREAD

**Issue by cecilehannay** [NCAR/ADF#192]
### ADF run type

Model vs. Model

### What happened?

The variables are ``single`` in the climo files but they are ``double`` in the climo-regrid files. 

We should change everything to ``single``

### ADF Hash you are using

682c95b

### What machine were you running the ADF on?

CISL machine

### What python environment were you using?

NPL (CISL machines only)

**Comment by brianpm** [comment]
I dug into this issue.

The method that ADF currently uses for this "regridding" is xarray's [`interp_like`](https://docs.xarray.dev/en/stable/generated/xarray.DataArray.interp_like.html). 

It took a little while, but I think I understand the behavior now, using this example. I'm using two real datasets, but it doesn't matter. The only salient points are that the data variable in the first Dataset is of type `float32`, the coordinate variables in that Dataset are also `float32`, and the second Dataset defines the target grid and has coordinate variables that are `float32`. In this example, I'm using `interp_like` to check the dtype of the output data and coordinates:

```python
ds = xr.open_dataset("tas_Amon_HadGEM3-GC31-LL_historical_r3i1p1f3_gn_195001-201412.nc")
ds2 = xr.open_dataset("HadCRUT.4.6.0.0.median.nc")
ds2 = ds2.rename({"latitude":"lat", "longitude":"lon"})

orig = ds['tas'].mean(dim='time')
print(f"Orig Data to get regridded: data type {orig.dtype}, coord types: {[f'({name}, {orig.indexes[name].dtype})' for name in orig.indexes]}")
print(f"Target data coord types: {ds2.lat.dtype}, {ds2.lon.dtype}")

# first: input data is float32, coords are float64
#        target grid is float32
#        result data is float64 w/ coords of float32
rgd1 = orig.interp_like(ds2)
print(f"[1] regrid type: {rgd1.dtype}, coords: {rgd1.lat.dtype}, {rgd1.lon.dtype}")

# second:
#   input data is float32, coords are float32
#   target grid is float32
#   result data float32 w/ coords of float32
orig32 = orig.copy()
orig32 = orig32.assign_coords({"lat":orig32.lat.astype('float32'), "lon":orig32.lon.astype('float32')})
print(f"Data to get regridded: data type {orig32.dtype}, coord types: {[f'({name}, {orig32.indexes[name].dtype})' for name in orig32.indexes]}")
rgd2 = orig32.interp_like(ds2)
print(f"[2] regrid type: {rgd2.dtype}, coords: {rgd2.lat.dtype}, {rgd2.lon.dtype}")  # all "single"

# third
#   input data is float32, coords float64
#   target gfid is float64
#   result data float64 w/ coords float64
print(f"Data to get regridded: data type {orig.dtype}, coord types: {[f'({name}, {orig.indexes[name].dtype})' for name in orig.indexes]}")
tgt2 = ds2.copy()
tgt2 = tgt2.assign_coords({"lat":ds2.lat.astype('float64'), "lon":ds2.lon.astype('float64')})
print(f"Target data coord types: {tgt2.lat.dtype}, {tgt2.lon.dtype}")
rgd3 = orig.interp_like(tgt2)
print(f"[3] regrid type: {rgd3.dtype}, coords: {rgd3.lat.dtype}, {rgd3.lon.dtype}")  # All "double"

# fourth: 
#   input data is float32, coords float32
#   target grid is float64
#   result
rgd3 = orig32.interp_like(tgt2)
print(f"[4] regrid type: {rgd3.dtype}, coords: {rgd3.lat.dtype}, {rgd3.lon.dtype}")  # All "double"
```

The output of this looks like:
```
Data to get regridded: data type float32, coord types: ['(lat, float64)', '(lon, float64)']
Target data coord types: float32, float32
[1] regrid type: float64, coords: float32, float32
Data to get regridded: data type float32, coord types: ['(lat, float32)', '(lon, float32)']
[2] regrid type: float32, coords: float32, float32
Data to get regridded: data type float32, coord types: ['(lat, float64)', '(lon, float64)']
Target data coord types: float64, float64
[3] regrid type: float64, coords: float64, float64
[4] regrid type: float64, coords: float64, float64
```

From this, my conclusion is that when using `interp_like`, the interpolated data is promoted to `float64` if any of the input or target grids are `float64`, and is only kept at `float32` when all the coordinate variables are also `float32`. The output coordinates are always the same as the target coordinates.

To "fix" this issue, we could do several things:
- check the dtype of the output and convert it to the input dtype if it changes
- convert the coordinate variables to be the same dtype as the input data (this is **not** a good option)
- change interpolation methods to use one that preserves the data's dtype

Thinking about the last option, I reviewed what happens using xESMF. It appears to preserve the output data as `float32` under all conditions. 

We have code in ADF to use xESMF. The change would require only switching the interpolation method kwarg. The question is whether we want to make xESMF a required dependency. Input from @nusbaume and @justin-richling would be useful. 

It also looks like GeoCAT's [`interp_multidim`](https://geocat-comp.readthedocs.io/en/latest/user_api/generated/geocat.comp.interpolation.interp_multidim.html#geocat.comp.interpolation.interp_multidim) might work. That's already a dependency, so would be attractive if it works. I was not able to test this yet because installing geocat-comp into the environment I am using would downgrade pandas, pint, and xarray. I'm not sure if that is geocat's fault or one of their dependencies. I will try to set up a different environment for testing the result.

**Comment by brianpm** [comment]
I spoke with @cecilehannay IRL about this. The original concern was about whether something about the calculation was incorrect.

Based on my above investigation, and discussion in https://github.com/NCAR/geocat-comp/issues/488, I think we have confidence that the calculation is correct, or at least as correct as we expected it to be.

I'm going to close this issue. There's change in precision isn't a concern, so we are okay on that front. We should consider moving our interpolation to an improved implementation (that understands longitude to be cyclic, in particular). I suggest the GeoCAT function since that would not add a new dependency.
