### ISSUE TITLE
Method to set per-variable defaults

### ISSUE THREAD

**Issue by andrewgettelman** [NCAR/ADF#50]
Greetings,

Starting with @brianpm comment on this: 

We need a way to specify defaults on a per-variable basis, as @andrewgettelman mentioned, and Adam Phillips brought up from the beginning. We didn’t build any support for this yet, but it could be as simple has having a file (json or yaml or csv or whatever), in which every entry looks something like this:

	Variable, scale_factor, to_units, cmap.  , diff_cmap, cnLevels.   , diff_cnLevels, map_projection
	PRECT   , 86400000.   , "mm/day", ‘BuGn’ , ‘BrBG’.  , (0, 100, 10), (-20, 20, 2), “Molleweide"

We can decide what fields need to be in there; this was just what occurred to me at this moment. Then plotting scripts could query this table if a flag (“amwg_defaults” ?) is set.

**Comment by brianpm** [comment]
Does anyone have a strong opinion about whether to have one big file that has all the variables vs. @andrewgettelman's suggestion of one file per variable? I don't really, but I see the potential attraction to one file per variable because one could just add new custom entries that are used for particular diagnostics (and ignored by everything else). 

Preference for YAML vs JSON vs something else? 
I'm ambivalent, but YAML is a little easier to edit by hand than JSON. There are other options, but I'm not sure whether it would be worth adding another file format to ADF unless there were a good reason.

**Comment by andrewgettelman** [comment]
If we are using YAML already for scripts (and easier to edit) suggest we stick with it and not add a file format to ADF as Brian suggests.

I am ambivalent to one file per variable or not. Easier to customize as Brian notes, but harder to manage.

Maybe a compromise is a format where there is one file with a 'block' for each variable that could contain any number of things (so could be customized). E.g.:
```
var1
- attribute1 = X
- attribute2 = "Y"

var2
- attribute3 = Z
- attribute2 = "Q"
```

**Comment by bitterbark** [comment]
I agree that YAML is better than JSON.

Advantages of multiple files:
- they can be developed in parallel, perhaps during a later hack-a-thon
- if we went with the .py format Andrew mentioned before, the deriving
could happen in those files. There would be some disadvantage with
formatting though.
- listing the files in a dir gives a more concise view than scrolling
through a file, and more customizable view (eg -ltr to find latest added)

**Comment by brianpm** [comment]
I started to work on an example, but haven't made it very far yet. I think for now I will just use one YAML file, but that can easily be broken into multiple files if that turns out to be better/preferred. For the example, I won't even touch the "library" code that is the main structure of ADF; I'll just put in a YAML file and modify one of the plotting examples. That'll be more of a proof of concept. Realistically, I might be able to make progress on this on Friday; if anyone wants to beat me to it, please do and let me know.

**Comment by andrewgettelman** [comment]
@brianpm : thanks for diving into this. If there is something I can do to help, let me know. I probably can't do much except test and modify a template, but happy to help if I can. This would certainly help help new users to contribute to the hackathon and enable us to rapidly build out a usable package. Thanks!

**Comment by nusbaume** [comment]
Thanks for working on this @brianpm!  I agree that having a single YAML file in the format that @andrewgettelman laid out is a good idea, at least as a starting place.  @bitterbark raised some valid concerns, but there may be potential workarounds to at least some of those issues that we could implement using the YAML file itself if need be.

Otherwise, please let me know if you need any help or assistance!  Also, if you end up making some progress but then need to stop work on it please let me know and I might be able to get it over the finish line.  Just let me know if that situation arises. 

Thanks!

**Comment by brianpm** [comment]
This is addressed by https://github.com/NCAR/ADF/pull/80
